### ISSUE TITLE
Checklist User stories

### ISSUE THREAD

**Issue by AnaCascante** [AnaCascante/semester-project2#1]
- [x] A user with a stud.noroff.no email may register 
- [x] A registerd user may login
- [x] A registerd user may logout
- [x] A registered user may update their avatar 
- [x] A registered user may view their total credit
- [x] A registered user may create a Listing with a title, deadline date, media gallery and description 
- [x] A registered user may add a Bid to another user's Listing
- [x] A registered user may view bids made on a listing 
- [x] An unregisterd user may serach through Listings
